<?php

/**
 * @file
 * Implements third party settings form for blocks and a preprocessor for
 * conditionally show and hiding blocks based on selected breakpoints.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function block_breakpoint_theme($existing, $type, $theme, $path) {
  return [
    'block_breakpoint_inline_match' => [
      'variables' => [],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function block_breakpoint_form_block_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\block_breakpoint\BlockBreakpointManager $block_breakpoint_manager */
  $block_breakpoint_manager = \Drupal::service('block_breakpoint.manager');
  $block_breakpoint_manager->blockFormAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function block_breakpoint_preprocess_block(&$variables) {
  /** @var \Drupal\block_breakpoint\BlockBreakpointManager $block_breakpoint_manager */
  $block_breakpoint_manager = \Drupal::service('block_breakpoint.manager');
  $block_breakpoint_manager->preprocessBlock($variables);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function block_breakpoint_form_layout_builder_configure_block_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\block_breakpoint\BlockBreakpointManager $block_breakpoint_manager */
  $block_breakpoint_manager = \Drupal::service('block_breakpoint.manager');
  $block_breakpoint_manager->blockFormAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function block_breakpoint_preprocess_layout(&$variables) {
  $layout = $variables['layout'] ?? NULL;
  if ($regions = $layout->getRegionNames()) {
    foreach ($regions as $region_name) {
      if (isset($variables['content'][$region_name])) {
        _block_breakpoint_layout_builder_add($variables, $region_name);
      }
    }
  }
}

/**
 * Helper function for adding attributes via layout builder.
 */
function _block_breakpoint_layout_builder_add(&$variables, $region_name) {
  /** @var \Drupal\block_breakpoint\BlockBreakpointManager $block_breakpoint_manager */
  $block_breakpoint_manager = \Drupal::service('block_breakpoint.manager');

  foreach ($variables['content'][$region_name] as &$section_component) {
    $block_breakpoint_manager->preprocessComponent($section_component);
  }
}
